### ISSUE TITLE
Additional Links don't work with example config. Please update

### ISSUE THREAD

**Issue by fbunduka** [mediabeastnz/silverstripe-fancy-devbuild#24]
Hi there, just a small issue here.
I created an additional link "Flush all" (see code below). Didn't work untill I used the lowercase "tasks" instead of "Tasks".
Please change the README.md accordingly or change in Code.

Thank you for the nice module, @mediabeastnz.

```
DevTasks:
  tasks:
    flush:
      title: "Flush all"
      link: /?flush=all
      reset_time: 5000 # Optional
      error_handler: newtab # Optional
      success_handler: ignore # Optional
```
